name: Create and Publish Docker Image
on:
 workflow_call:
  inputs:
   image_name:
    required: true
    type: string
   tag:
    type: string
  secrets:
   DOCKERHUB_USERNAME:
    required: true
   DOCKERHUB_PASSWORD:
    required: true
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Login to the Registry
     uses: docker/login-action@v1
     with:
      registry: https://hub.docker.com
      username: $((secrets.DOCKERHUB_USERNAME))
      password: $((secrets.DOCKERHUB_PASSWORD))
      
   - name: Set the tag
     run: |
      if [ -z "${{inputs.tag}}"]
      then
       echo "final_tag-latest" >> $GITHUB_ENV
      else
       echo "final_tag-${{inputs.tag}}" >> $GITHUB_ENV
      fi
   - name: Build and Push the image
     run: |
     
      dockerfile: Sivainfomagnus/resuable-workflow-template/Dockerfile
                  docker build -t my-web-awesome-app:1.0 .
      
 do_something_else:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello"
