name: Create and Publish Docker Image
on:
 workflow_call:
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Build the docker image
     run: docker build -t myapp:1.0 .
   - name: Build and Push the image
     uses: docker/build-push-acton@v2.7.0
     with:
      context: .
      file: Sivainfomagnus/resuable-workflow-template/Dockerfile
      push: true
     env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
      
 do_something_else:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello"
