name: Create and Publish Docker Image
on:
 workflow_call:
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Build the docker image
     run: docker build -t myapp:1.0 .
   - name: Login to Docker Hub
     uses: dokcer/login-action@v1
     with:
      username: ${{secrets.DOCKERHUB_USERNAME}}
      password: ${{secrets.DOCKERHUB_ACCESS_TOKE}}
 do_something_else:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello"
