name: Create and Publish Docker Image
on:
 workflow_call:
  inputs:
   image_name:
    required: true
    type: string
   tag:
    type: string
  secrets:
   DOCKERHUB_USERNAME:
    required: true
   DOCKERHUB_ACCESS_TOKEN:
    required: true
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Build and Push the image
     run: docker build -t myapp:1.0
      
 do_something_else:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello"
