name: Create and Publish Docker Image
on:
 workflow_call:
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v1
     
   - name: Build and Push the image
     uses: docker/build-push-acton@v2
     with:
      registry: https://hub.docker.com
      context: .
      dockerfile: ./Sivainfomagnus/resuable-workflow-template/Dockerfile
      
 do_something_else:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello"
