name: Create and Publish Docker Image
on:
 workflow_call:
  inputs:
   image_name:
    required: true
    type: string
   tag:
    type: string
  secrets:
   registry_username:
    required: true
   registry_password:
    required: true
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Setup BuildX
     uses: docker/setup-buildx-action@v2.5.0
     
   - name: Login to the Registry
     uses: docker/login-actions@v2.1.0
     with:
      registry: https://hub.docker.com
      username: $((secrets.registry_username))
      password: $((secrets.registry.password))
      
   - name: Set the tag
     run: |
      if [ -z "${{inputs.tag}}"]
      then
       echo "final_tag-latest" >> $GITHUB_ENV
      else
       echo "final_tag-${{inputs.tag}}" >> $GITHUB_ENV
      fi
   - name: Build and Push the image
     uses: docker/build-push-acton@v4.0.0
     with:
      registry: https://hub.docker.com
      context: .
      push: true
      tags: ${{secrets.registry_username}}/${{inputs.image_name}}:${{env.final_tag}}
      dockerfile: Sivainfomagnus/resuable-workflow-template/Dockerfile
      
 do_something_else:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello"
