name: Reusable workflow user

on:
 workflow_dispatch:
 push:
  branches:
   - main
jobs:
 do-it:
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   
   - name: Run a one-line script
     run: echo Hello, world!
     
 docker:
  uses: Sivainfomagnus/resuable-workflow-template/.github/workflows/Docker-image.yml@main
  with:
   image_name: my-awesome-app
   tag: $GITHUB-RUN-NUMBER
  secrets:
   DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
   DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
